### ISSUE TITLE
Updating show broken

### ISSUE THREAD

**Issue by legolasmcm** [ltguillaume/droidshows#84] opened 2020-03-14 07:06 UTC
Never had an issue updating with any version I've used. Always worked for me untill the past 3 days or so. Some shows update, some don't. Not sure if anybody else is experiencing this or not.

**Comment by casperklein** [comment] 2020-03-14 11:14
I noticed the same. I am pretty sure, that is an upstream problem of thetvdb.com. There is an option in the settings, to use a tvdb mirror. However, that suffers from the same problem.

**Comment by ltguillaume** [comment] 2020-03-14 11:39
Saw the same thing happening yesterday. It's just a timeout, so probably capacity problems with TheTVDB.com. They've always had periods like this. Perhaps you can find some info about it on their forums.

**Comment by legolasmcm** [comment] 2020-03-14 16:51
Appreciate your time, mate.

**Comment by ltguillaume** [comment] 2020-03-14 17:54
Leaving this open to be revisited in a couple of days.

**Comment by legolasmcm** [comment] 2020-03-16 00:48
I just checked this feature. It appears it has been resolved and mine got through every update and it did it in the normal amount of time.

**Comment by ltguillaume** [comment] 2020-03-16 05:35
Great! I'll close the issue, but don't hesitate to comment here again if it happens again or if you find some relevant info about it.

**Closed as completed by ltguillaume** 2020-03-16 05:35 UTC
Labels: thetvdb

**Comment by beerisgood** [comment] 2020-04-04 18:28
@ltGuillaume 
Looks like the problem is back. Using the tvdb mirror doesn't help

I also wonder why only tvdb mirror is used, no matter if it's disabled or not.
Maybe this is the reason why updates failed?

**Comment by ltguillaume** [comment] 2020-04-04 18:55
I don't understand what you mean. The main URL used is https://thetvdb.com. The mirror is https://thetvdb.plexapp.com.

**Comment by ltguillaume** [comment] 2020-04-04 19:01
See https://forums.thetvdb.com/viewtopic.php?f=17&t=63137&start=20
