### ISSUE TITLE
App crash due to network exceptions

### ISSUE THREAD

**Issue by njumzs** [ltguillaume/droidshows#16] opened 2016-04-26 06:18 UTC
DroidShows 7.0.4, this bug affects all Android versions

In the DroidShows.java:772:
**Serie sToUpdate  = theTVDB . getSerie(serieId, langCode);**
If the network connection breaks at this time point, the XMLParser in getSerie would return a null Serie object, and cause a subsequent null pointer exception crash.

**Comment by ltguillaume** [comment] 2016-04-26 12:47
Will be fixed in next release, thank you!

**Comment by ltguillaume** [comment] 2016-04-26 14:09
@njumzs 
I can't reproduce the crash myself, so could you try this version and tell me if it's fixed?
[links removed]

**Comment by njumzs** [comment] 2016-04-27 10:15
This bug is found by an automatic tool. We ran the tool for the latest version and we are not able to find any such kind of issue.

**Comment by ltguillaume** [comment] 2016-04-27 16:16
Thanks! And that sounds interesting, what tool did you use? I haven't yet uploaded the commit with these changes, so it can't be a tool that runs over the source code.

**Comment by njumzs** [comment] 2016-04-28 01:09
@ltGuillaume 
It is a tool we are developing far from completed. And it can conduct testing from an apk file.

**Comment by ltguillaume** [comment] 2016-04-28 01:19
Sounds really cool! (How) can I be kept up-to-date on its development?

**Comment by jiangyy** [comment] 2016-04-28 02:06
Sure! The network exception testing is only one component of the tool. When more functions are added to the tool, we will run regression test on all previously tested apps, and any more bug found will be reported.

It's currently a little bit difficult for a third-party to run the tool: we modified Android Runtime with some low-level hacks. When the project is ready, we will absolutely make it open source :)

**Comment by njumzs** [comment] 2016-04-28 02:24
@jiangyy 
Aha！

**Comment by ltguillaume** [comment] 2016-04-28 14:17
@jiangyy
So you improved upon the Android Testing Tools or something? I see you've already evaluated (some improved implementations of) the ATT in the 2015 paper on your website. Cool :)

**Comment by jiangyy** [comment] 2016-04-28 14:25
ATT is rather simple and immature. We are working on a much more advanced tool (and we intended to integrate it into ATT someday), basically based on modifying the Android Runtime (ART). Technically, the modified ART runs in interpretation mode, such that we easily "hijack" every executed instruction. For example, we can intercept the internal Socket invocations and inject failures (delays, or thrown IOException). This is roughly how this bug is found :)

**Comment by ltguillaume** [comment] 2016-04-28 16:53
Sounds great! :+1:

**Closed as completed by ltguillaume** 2016-04-28 16:53 UTC
Labels: bug, fixed
